# Generated by Django 3.1.6 on 2021-02-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(blank=True, max_length=100, null=True)),
                ('ongoing', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
